scylladb/scylla-java-driver-matrix

run.py
Fix this issue
```
04:06:53  Traceback (most recent call last):
04:06:53    File "main.py", line 39, in <module>
04:06:53      main(arguments.java_driver_git, arguments.scylla_install_dir, arguments.tests, versions, arguments.scylla_version)
04:06:53    File "main.py", line 14, in main
04:06:53      results.append(run.Run(java_driver_git, scylla_install_dir, version, tests, scylla_version=scylla_version))
04:06:53    File "/data/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 14, in __init__
04:06:53      self._run()
04:06:53    File "/data/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 58, in _run
04:06:53      for ignore_element in self._ignoreSet():
04:06:53 …
```
=> fix(run.py): Using `safe_load` inside `load`

versions/scylla/3.10.2.1/ignore.yaml, versions/scylla/3.7.1.0/ignore.yaml
Ref: https://github.com/scylladb/scylla-ccm/pull/393
=> Ignore jmx base test, since ccm uses diffrent address for jmx

versions/datastax/4.12.0/ignore.yaml, versions/datastax/4.12.1/ignore.yaml, versions/datastax/4.13.0/ignore.yaml
since a recent fix in scylla make this test irelevent,
it was decided to skip this test from now on
Close: https://github.com/scylladb/scylla/issues/10956
=> Skip BoundStatementCcmIT.should_set_all_occurrences_of_variable

scripts/run_test.sh
seems like now that we use unifed package, we are failing the java version check case of a warning, that break the `install.sh` code:
```
java -version
Picked up _JAVA_OPTIONS: -Duser.home=/home/fruch
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-8u322-b06-1~deb9u1-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)
```
so we are removing those flags, seems like they aren't needed anymore.
=> Remove _JAVA_OPTIONS env variable

versions/datastax/4.13.0/patch, versions/datastax/4.17.0/ignore.yaml, versions/datastax/4.17.0/patch, versions/scylla/4.17.0.0/ignore.yaml, versions/scylla/4.17.0.0/patch
experimental flag isn't supported anymore by scylla
Ref: scylladb/scylla-ccm#512
Fixes: #24
=> use `experimental_features:[udf]` and not `experimental: true`

versions/datastax/4.17.0/ignore.yaml
This test fails on protocol v4 with: `Can't use nowInSeconds with
protocol V4`.
Fixes #27
=> datastax: Ignore com.datastax.oss.driver.core.cql.NowInSecondsIT

scripts/run_test.sh
This change fixes an issue where tests would try to share configuration
with child containers via /tmp, but since those directories are not mounted and
a parent docker socket is used the containers created this way would
receive incorrect mounts. This fixes issues with SniProxy tests.
Fixes #28
=> run_test.sh: Mount /tmp into the unit test container

versions/datastax/4.18.0/ignore.yaml, versions/datastax/4.18.0/patch
Main difference with 4.17.0 is imports in BaseCcmRule.
Fixes #35
=> datastax: add patch for 4.18.0

scripts/Dockerfile, scripts/image
without it cqlsh on older branches like 5.2, would fail to work and the sni test are using cqlsh in ccm flow
Fixes: #37
=> introudce back python2 into the docker image

versions/scylla/3.11.2.4/ignore.yaml
One of the tests in this class uses an unsupported option and the
ScyllaSkip annotation seems to first skip, then fail the test anyway due
to this.
Closes #41
Closes #34
=> scylla-3.x: Ignore ReconnectionTest

versions/scylla/3.11.2.4/patch
This makes the test execute properly on scylla, as before the test would
crash with an assertion error (scylladb/scylladb#16252).
Fixes scylladb/java-driver#250
=> scylla-3.x: Increase networking-io-control-blocks for SessionStressTest

versions/datastax/4.18.0/ignore.yaml
As Scylla does not support protocol version 5 for java-driver those
tests should be skipped.
=> datastax: Ignore V5 protocol tests on 4.18.0

versions/scylla/4.15.0.0/patch, versions/scylla/4.17.0.0/patch
PeersV2NodeRefreshIT test is not closing its test session, which leaks into SessionLeakIT tests and causes the should_warn_when_session_count_exceeds_threshold test to fail.
The change adds an After cleanup method to ensure that the test session is closed after the test and is not leaked / affecting any other subsequent tests.
Fixes: https://github.com/scylladb/scylla-java-driver-matrix/issues/46.
The change was tested in master java-driver-matrix pipeline: [scylla-master-java-driver-matrix-test](https://jenkins.scylladb.com/job/scylla-staging/job/dimakr/job/scylla-master-java-driver-matrix-test/24/) (please note that the datastax version of the driver was deliberately skipped in the build, to not run the corresponding stage and save time. This results in the expected fail of this stage. …
=> scylla-4.x: Update 4.15.0.0 and 4.17.0.0 patches

scripts/run_test.sh
since cqlsh move to use shiv, it's using
this folder `~/.shiv` as a place to extract
in this docker envirment, it didn't exist, and
the user didn't had premission to create it.
mounting it as tmpfs fixes the issue.
=> scripts/run_test.sh: create `~/.shiv` as tmpfs

versions/scylla/3.11.4.0/ignore.yaml, versions/scylla/3.11.4.0/patch
Order of operations: checkout driver 3.11.4.0, apply 3.11.2.4 patch, apply old 3.11.4.0 patch, generate the new patch file and replace 3.11.4.0 patch file. All patches applied cleanly without conflicts.
Fixes #56.
=> Rebase 3.11.4.0 patch on top of 3.11.2.4 patch

versions/datastax/4.18.1/ignore.yaml, versions/datastax/4.18.1/patch
Copied over ignores and patch from 4.18.0 then resolved patch conflicts with 4.18.1 to generate a new one.
=> Add patch for datastax 4.18.1

versions/scylla/3.11.4.0/patch
Checks out the newer version of CCMBridge and adds the adjustments to StateListenerTest.
=> Update 3.11.4.0 scylla patch

versions/scylla/4.18.0.2/ignore.yaml, versions/scylla/4.18.0.2/patch
Based on the patch for 4.18.0.1.
Leaves the CCMBridge's change to idPrefix instead of ipPrefix in, changes new tests to use withIdPrefix. Leaves the swap to 'scylla.version' instead of 'ccm.version' in.
=> Add patch for scylla 4.18.0.2 version

versions/scylla/3.11.5.3/patch
Checks out a newer version of CCMBridge.
Removes hardcoded in patch Scylla version.
Adds TestNG provider for surefire plugin.
=> More adjustments for scylla patch 3.11.5.3

versions/scylla/3.11.4.0/patch
Due to a bug StateListenerTest sets up wrong expectation for Scylla versions 2025.1.x. Fixes comparison responsible for that.
=> Add bugfix for scylla 3.11.4.0 patch

versions/scylla/4.18.0.2/patch
Wrong ip string was causing endless reconnection loop
=> Fix typo in patch version scylla 4.18.0.2

versions/scylla/3.10.2.1/ignore.yaml, versions/scylla/3.11.0.1/ignore.yaml, versions/scylla/3.11.2.4/ignore.yaml, versions/scylla/3.11.4.0/ignore.yaml, versions/scylla/3.11.5.3/ignore.yaml, versions/scylla/3.7.1.0/ignore.yaml
Adds to ignores the following methods of TableMetadataTest class: should_parse_compact_dynamic_table,
should_parse_compact_static_table,
should_parse_compact_table_with_multiple_clustering_columns, should_parse_dense_table.
All those methods fail with InvalidQueryException: InvalidQuery Support for the deprecated feature of 'CREATE TABLE WITH COMPACT STORAGE' is disabled and will eventually be removed in a future version.  To enable, set the 'enable_create_table_with_compact_storage' config option to 'true'.
=> Ignore chosen TableMetadataTest methods

run.py
Adds one small mkdir. Without it the first version in the test trips up on lack of directory.
=> Create reports directory before using it

versions/scylla/4.18.0.2/patch
After the change to idPrefix the ip still needs to be passed with `-i` when adding new nodes. Otherwise the ip wont match with the prefix set by `--id`
=> 4.18.0.2 patch: Add ip to `ccm add node`

versions/scylla/3.11.4.0/ignore.yaml, versions/scylla/3.11.4.0/patch, versions/scylla/3.11.5.3/ignore.yaml, versions/scylla/3.11.5.3/patch, versions/scylla/3.11.5.4/ignore.yaml, versions/scylla/3.11.5.4/patch
Replaces method level exclusions from ignore.yaml for versions:
3.11.4.0, 3.11.5.3, 3.11.5.4
Temporary solution for issue #80 that should unblock testing.
Whitespace was added before `#` symbols specifying methods for easier
reenablement once cause is resolved.
3.11.5.4: Add test fixes to the patch
Adds minor changes to ControlConnectionTest and DnsEndpointTest
that should fix those tests. One is improved by removing keyspace name
collision and the other by cleaning up mock hostnames.
3.11.4.0: Add unique keyspace name to ControlConnectionTest
=> Collection of fixes

versions/datastax/4.19.0/ignore.yaml, versions/datastax/4.19.0/patch
Adds patch for cassandra-java-driver 4.19.0.
Exists under versions/datastax directory similarly to versions predating the donation to apache.
Many test methods were ignored instead of added to ignore.yaml to avoid the issue #80. Conflicts were resolved mostly in favor of 4.19.0. Minimal changes were made to CcmBridge to ensure the driver matrix will still run correctly.
=> Patch for datastax 4.19.0

versions/scylla/4.18.0.2/patch
Allows blocking calls inside
`com.datastax.oss.driver.shaded.guava.common.collect.MapMakerInternalMap#put`
=> scylla/4.18.0.2: Add Blockhound exception for ConcurrentMap

run.py
Fix following error:
```
20:02:35  ERROR:root:4.19.0.0 failed
20:02:35  Traceback (most recent call last):
20:02:35    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/main.py", line 31, in main
20:02:35      report = runner.run()
20:02:35               ^^^^^^^^^^^^
20:02:35    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 142, in run
20:02:35      if exclude_str := ','.join(f"!{ignore_element}" for ignore_element in self.ignore_tests):
20:02:35                                                                            ^^^^^^^^^^^^^^^^^
20:02:35    File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
20:02:35      val = self.func(instance)
20:02:35 …
```
=> Make it work properly when there are no tests to ignore

run.py
When provided with empty list of tests to ignore (e.g. just "tests:" string), `yaml.safe_load(file)` will produce a dict containing key `'tests'` with value `None`. This results in TypeError since `None` is not iterable. This change adds one extra check for `None` value.
=> Check if list of tests to ignore is parsed as `None`

run.py
After `4.19.0.0` cli requires `-Dccm.distribution=scylla` or `-Dccm.scylla` to be present alongside with `-Dccm.version`.
Before it required `-Dccm.scylla` and `-Dccm.version` and even before that just `-Dscylla.version`.
We also plan to remove `-Dccm.scylla` in favor of `-Dccm.distributon=scylla`.
This PR combines all of that to make sure cli matches all the requirements for all possible version.
=> Update 4.x scylla driver test cli

scripts/Dockerfile
Manually installs Maven version 3.9.10.
The highest version that package manager sees with current setup is 3.6.0 which is not sufficient for some of the newer plugins in recent java-driver versions.
This will break any archaic versions that require Java older than 8.
=> Manually install Maven 3.9.10 in Dockerfile

main.py, processjunit.py, run.py
Previously the matrix would run integration testing through surefire plugin during the `test` phase instead of `integration-test`. Surefire plugin is generally considered to be made for unit testing and not integration testing.
Such setup makes it skip configuration included in pom.xml for integration testing that is tied to the failsafe plugin.
In order to return to proper setup this change switches to running `integration-test` phase which is handled by maven-failsafe-plugin. 
This includes a few adjustments which are:
The reports directory is now `failsafe-reports` and not `surefire-reports` (4.x), 
the test report pattern now includes the `TEST-` prefix which skips unexpected summary files for the groups of tests,
`-Dtest='<ignore list>'` was replaced with appropriate for failsafe …
=> Switch to running integration-test phase for 4.x versions

versions/datastax/4.18.1/patch, versions/datastax/4.19.0/patch, versions/scylla/4.18.1.0/patch, versions/scylla/4.19.0.0/patch
Backports fix to metrics ITs that makes them serial instead. Those tests interfere with each other when run concurrently.
See commit e2533ea76b2aa61e629e841facca1c2f653dac1f in scylladb/java-driver for more details.
=> Backport fix to metrics ITs
